# This file defines the CI build steps for this repo.
#
# Documentation for this file format is here:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

variables:
  FORCE_COLOR: 1

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: 'Use Node 12'
  inputs:
    versionSpec: '12.x'
    checkLatest: true

- script: 'git config --local user.email dpreleasebot@hbo.com'
  displayName: 'git config email'

- script: 'git config --local user.name hbo-github-bot'
  displayName: 'git config name'

- script: 'npm install'
  displayName: 'Install: wiremock-captain'

- script: 'npm run build'
  displayName: 'Build: wiremock-captain'

- script: 'npm run build'
  displayName: 'Test: wiremock-captain'

- script: 'npm install'
  displayName: 'Install: express-app demo project'
  workingDirectory: examples/express-app

- script: 'npm run build'
  displayName: 'Build: express-app demo project'
  workingDirectory: examples/express-app
